name: dont_poop_in_my_phone
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.9+14

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  bot_toast: ^4.0.3
  permission_handler: ^10.0.0
  path_provider: ^2.0.11
  flutter_spinkit: ^5.1.0
  dio: ^4.0.6
  package_info: ^2.0.2
  url_launcher: ^6.1.5
  intro_views_flutter: ^3.2.0
  shared_preferences: ^2.0.15
  device_info_plus: ^4.1.2
  flutter_breadcrumb: ^1.0.1
  open_filex: ^4.3.2
  mime: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "resource/icon正方形.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/json/