name: dont_poop_in_my_phone
description: don't poop in my phone, clean the rubbish.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.10+15

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  bot_toast: ^4.0.3
  permission_handler: ^10.2.0
  path_provider: ^2.0.12
  flutter_spinkit: ^5.1.0
  dio: ^4.0.6
  package_info: ^2.0.2
  url_launcher: ^6.1.9
  intro_views_flutter: ^3.2.0
  shared_preferences: ^2.0.17
  device_info_plus: ^8.1.0
  flutter_breadcrumb: ^1.0.1
  open_filex: ^4.3.2
  mime: ^1.0.4
  intl: ^0.18.0
  storage_space: ^1.0.1+5
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "resource/icon正方形.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/json/